_wandb:
    value:
        cli_version: 0.24.0
        e:
            r6crdmvwlfasddyrx0rn1e9trdj9ppjt:
                args:
                    - '@/work/grana_far2023_fomo/ChestXray/args.txt'
                codePath: baseline_net.py
                codePathLocal: baseline_net.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "214643507200"
                        used: "28606316544"
                email: gabrielerosati97@gmail.com
                executable: /work/grana_far2023_fomo/ChestXray/Chest/bin/python
                git:
                    commit: 3f9ad3431293b2d1597371aa67e47d0c8c662b69
                    remote: git@github.com:gabri1997/chest_x_ray.git
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-343861d6-1a10-387b-855a-8b530ee739af
                host: patagarro
                memory:
                    total: "540712648704"
                os: Linux-5.15.0-144-generic-x86_64-with-glibc2.35
                program: /work/grana_far2023_fomo/ChestXray/baseline_net.py
                python: CPython 3.11.5
                root: /work/grana_far2023_fomo/ChestXray/wandb
                slurm:
                    cluster_name: aimagelab
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: grana_maxillo
                    job_cpus_per_node: "4"
                    job_end_time: "1769530847"
                    job_gid: "506"
                    job_gpus: "0"
                    job_id: "2712465"
                    job_name: ChestXray_train
                    job_nodelist: patagarro
                    job_num_nodes: "1"
                    job_partition: all_usr_prod
                    job_qos: normal
                    job_start_time: "1769444447"
                    job_uid: "52290"
                    job_user: grosati
                    jobid: "2712465"
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: patagarro
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /work/grana_far2023_fomo/ChestXray
                    submit_host: ailb-login-03
                    task_pid: "3459804"
                    tasks_per_node: "1"
                    topology_addr: patagarro
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                startedAt: "2026-01-26T16:24:29.994869Z"
                writerId: r6crdmvwlfasddyrx0rn1e9trdj9ppjt
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
            "2":
                - 1
                - 41
                - 49
                - 51
            "3":
                - 16
            "4": 3.11.5
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 34
gamma:
    value: 0.1
learning_rate:
    value: 0.0001
momentum:
    value: 0.9
net_type:
    value: vit
num_epochs:
    value: 50
step_size:
    value: 7
weight_decay:
    value: 1e-05
